### ISSUE TITLE
Can I use Sidesplitter for 3D classification?

### ISSUE THREAD

**Issue by cfernande1470** [StructuralBiology-ICLMedicine/SIDESPLITTER#1]
Hi.
I am working on a membrane protein dataset. I've been running sidesplitter for 3D refinement and apparently is working good since the overfitting of the detergent belt is gone in my refinements.

However I still can not get a perfect reconstruction, and my transmembrane part is fuzzy and not well defined. When we try a 3D classification the overfitting problem come back, so we are wondering if there is any way to include Sidesplitter filtering in a 3D classification.

Thanks

**Comment by StructuralBiology-ICLMedicine** [comment]
This is something that can indeed be approached with similar methods, but cannot provide the same kinds of guarantees that SIDESPLITTER provides given the lack of independent half-maps. We have explorded this in quite some detail, before finally deciding in the end not to provide releases enabling this because of this lack of possible guarantees. Best, Chris
